# Generated by Django 5.1.3 on 2024-11-15 02:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=200)),
                ("customer_email", models.EmailField(max_length=254)),
                ("shipping_rate_id", models.CharField(max_length=200)),
                ("shipping_name", models.CharField(max_length=200)),
                ("shipping_address_line1", models.CharField(max_length=200)),
                (
                    "shipping_address_line2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("shipping_city", models.CharField(max_length=200)),
                ("shipping_postal_code", models.CharField(max_length=200)),
                ("shipping_state", models.CharField(max_length=200)),
                ("shipping_country", models.CharField(max_length=200)),
                ("subtotal_cents", models.IntegerField()),
                ("shipping_cents", models.IntegerField()),
                ("total_cents", models.IntegerField()),
                ("currency", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_payment_intent_id", models.CharField(max_length=200)),
                ("subtotal_cents", models.IntegerField()),
                ("shipping_cents", models.IntegerField()),
                ("shipping_stripe_id", models.CharField(max_length=200)),
                ("total_cents", models.IntegerField()),
                ("currency", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping_via", models.CharField(max_length=200)),
                (
                    "expected_delivery_days",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("tracking_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("shipped", "Shipped"), ("delivered", "Delivered")],
                        default="shipped",
                        max_length=20,
                    ),
                ),
                (
                    "shipment_started_email_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "shipment_completed_email_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
