# Generated by Django 5.1.3 on 2024-11-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artwork",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="artwork",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
