# Generated by Django 5.1.3 on 2024-11-08 00:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0002_alter_artwork_options_artwork_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=200)),
                ("customer_email", models.EmailField(max_length=254)),
                ("shipping_rate_id", models.CharField(max_length=200)),
                ("shipping_name", models.CharField(max_length=200)),
                ("shipping_address_line1", models.CharField(max_length=200)),
                ("shipping_address_line2", models.CharField(max_length=200)),
                ("shipping_city", models.CharField(max_length=200)),
                ("shipping_postal_code", models.CharField(max_length=200)),
                ("shipping_state", models.CharField(max_length=200)),
                ("shipping_country", models.CharField(max_length=200)),
                ("total_cents", models.IntegerField()),
                ("currency", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_payment_intent_id", models.CharField(max_length=200)),
                ("subtotal_cents", models.IntegerField()),
                ("shipping_cents", models.IntegerField()),
                ("shipping_stripe_id", models.CharField(max_length=200)),
                ("total_cents", models.IntegerField()),
                ("currency", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="artwork.order"
                    ),
                ),
            ],
        ),
    ]
