# Generated by Django 5.1.3 on 2024-11-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0003_order_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address_line2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
