# Generated by Django 5.1.3 on 2024-11-08 00:33

import django.db.models.deletion
from django.db import migrations, models


def convert_order_ids_to_foreign_keys(apps, schema_editor):
    Artwork = apps.get_model("artwork", "Artwork")
    Order = apps.get_model("artwork", "Order")

    for artwork in Artwork.objects.all():
        if hasattr(artwork, "order_id") and artwork.order_id:
            try:
                order = Order.objects.get(id=artwork.order_id)
                artwork.new_order = order
                artwork.save()
            except Order.DoesNotExist:
                # Handle cases where the order doesn't exist
                artwork.new_order = None
                artwork.save()


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0004_alter_order_shipping_address_line2"),
    ]

    operations = [
        # Add temporary field
        migrations.AddField(
            model_name="artwork",
            name="new_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="artwork.order",
            ),
        ),
        # Copy data
        migrations.RunPython(convert_order_ids_to_foreign_keys),
        # Remove old field
        migrations.RemoveField(
            model_name="artwork",
            name="order",
        ),
        # Rename new field to original name
        migrations.RenameField(
            model_name="artwork",
            old_name="new_order",
            new_name="order",
        ),
    ]
