# Generated by Django 5.1.3 on 2024-11-08 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0006_alter_artwork_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artworks",
                to="artwork.order",
            ),
        ),
    ]
