# Generated by Django 5.1.3 on 2024-11-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0007_alter_artwork_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artwork",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="artwork",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
    ]
