# Generated by Django 5.1.3 on 2024-11-08 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0008_alter_artwork_options_artwork_sort_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artwork",
            old_name="creation_date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
