# Generated by Django 5.1.3 on 2024-11-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0011_alter_payment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_cents",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal_cents",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
