# Generated by Django 5.1.3 on 2024-11-08 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0012_order_shipping_cents_order_subtotal_cents"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping_via", models.CharField(max_length=200)),
                (
                    "expected_delivery_days",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("tracking_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artworks",
                    models.ManyToManyField(
                        help_text="The artworks included in this shipment. Must be from the associated order.",
                        related_name="shipments",
                        to="artwork.artwork",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="artwork.order",
                    ),
                ),
            ],
        ),
    ]
