# Generated by Django 5.1.3 on 2024-11-08 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0013_shipment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="artworks",
        ),
        migrations.AddField(
            model_name="artwork",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artworks",
                to="artwork.shipment",
            ),
        ),
    ]
