# Generated by Django 5.1.3 on 2024-11-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0014_remove_shipment_artworks_artwork_shipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("sold", "Sold"),
                    ("unavailable", "Unavailable"),
                ],
                max_length=20,
            ),
        ),
    ]
