# Generated by Django 5.1.3 on 2024-11-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0015_alter_artwork_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="shipment_completed_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_started_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[("shipped", "Shipped"), ("delivered", "Delivered")],
                default="shipped",
                max_length=20,
            ),
        ),
    ]
