# Generated by Django 5.1.3 on 2024-11-15 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0016_shipment_shipment_completed_email_sent_at_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="order",
        ),
        migrations.AlterField(
            model_name="artwork",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artworks",
                to="orders.order",
            ),
        ),
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.AlterField(
            model_name="artwork",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artworks",
                to="orders.shipment",
            ),
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Shipment",
        ),
    ]
