# Generated by Django 5.1.3 on 2024-11-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0017_remove_shipment_order_alter_artwork_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="size",
        ),
        migrations.AddField(
            model_name="artwork",
            name="category",
            field=models.CharField(
                choices=[
                    ("figure", "Figure"),
                    ("landscape", "Landscape"),
                    ("multi_figure", "Multi-Figure"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artwork",
            name="height_inches",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artwork",
            name="medium",
            field=models.CharField(
                choices=[
                    ("oil_panel", "Oil on Panel"),
                    ("acrylic_panel", "Acrylic on Panel"),
                    ("oil_mdf", "Oil on MDF"),
                    ("oil_paper", "Oil on Oil Paper"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artwork",
            name="painting_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artwork",
            name="painting_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artwork",
            name="paper",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="artwork",
            name="width_inches",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="artwork",
            name="status",
            field=models.CharField(
                choices=[
                    ("sold", "Sold"),
                    ("available", "Available"),
                    ("coming_soon", "Coming Soon"),
                    ("unavailable", "Unavailable"),
                ],
                max_length=20,
            ),
        ),
    ]
