# Generated by Django 5.1.3 on 2024-11-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0018_remove_artwork_size_artwork_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="sold_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
