# Generated by Django 5.1.3 on 2024-11-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0019_artwork_sold_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="status",
            field=models.CharField(
                choices=[
                    ("sold", "Sold"),
                    ("available", "Available"),
                    ("coming_soon", "Coming Soon"),
                    ("not_for_sale", "Not for Sale"),
                    ("unavailable", "Unavailable"),
                ],
                max_length=20,
            ),
        ),
    ]
