# Generated by Django 5.2.6 on 2025-09-27 22:23

import artwork.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0020_alter_artwork_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_height',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_width',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=artwork.models.artwork_image_upload_path),
        ),
    ]
