from .base import *

SERVER_IP = os.getenv("SERVER_IP")
PRODUCTION_DOMAIN = os.getenv("PRODUCTION_DOMAIN")

DEBUG = True

BASE_URL = env("DEVELOPMENT_BASE_URL")
FRONTEND_URL = env("DEVELOPMENT_FRONTEND_URL")
TESTING_EMAIL_RECIPIENT = env("TESTING_EMAIL_RECIPIENT")

ALLOWED_HOSTS = ["localhost", "127.0.0.1", SERVER_IP, PRODUCTION_DOMAIN]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
