from .base import *

DEBUG = False

DOMAIN = env("PRODUCTION_DOMAIN")
ALLOWED_HOSTS = [DOMAIN, f"www.{DOMAIN}"]
STATIC_ROOT = env("STATIC_ROOT")
MEDIA_ROOT = env("MEDIA_ROOT")

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [f"https://{DOMAIN}", f"https://www.{DOMAIN}"]

# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"

SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_HTTPONLY = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]
