from .base import *

DOMAIN = env("PRODUCTION_DOMAIN")


DEBUG = False

ALLOWED_HOSTS = [DOMAIN, f"www.{DOMAIN}"]
STATIC_ROOT = env("STATIC_ROOT")
MEDIA_ROOT = env("MEDIA_ROOT")

SESSION_COOKIE_DOMAIN = DOMAIN
SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [f"https://{DOMAIN}", f"https://www.{DOMAIN}"]
CSRF_COOKIE_DOMAIN = DOMAIN
CSRF_TRUSTED_ORIGINS = [f"https://{DOMAIN}", f"https://www.{DOMAIN}"]
CSRF_COOKIE_SECURE = True

# SECURE_SSL_REDIRECT = True
# SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

X_FRAME_OPTIONS = "DENY"

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]
