name: Build Frontend

on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Build frontend
        working-directory: frontend
        env:
          VITE_API_HOST: ${{ secrets.VITE_API_HOST }}
          VITE_ENABLE_SENTRY: ${{ secrets.VITE_ENABLE_SENTRY }}
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist/

  deploy:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deploy-frontend-pages.outputs.page_url }}

    steps:
      - name: Deploy frontend
        uses: actions/deploy-pages@v4
        id: deploy-frontend-pages
        with:
          artifact_name: frontend-build
